{{ if or (eq (include "performInstallAndDeployment" .) "true") (eq (include "performUpgradeAndDeployment" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "installerJobReaderRole" }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["jobs", "deployments", "statefulsets"]
  verbs: ["get", "watch", "list"]
{{ end }}
